apiVersion: v1
kind: Service
metadata:
  name: jarvis
  namespace: statex-apps
  labels:
    app: jarvis
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: jarvis
  ports:
    - protocol: TCP
      port: 4870
      targetPort: 4870
      name: http
